CREATE SCHEMA IF NOT EXISTS `OficinaMecanica` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `OficinaMecanica` ;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`Mecanico` (
    CPF VARCHAR(14) PRIMARY KEY UNIQUE NOT NULL,
    nome VARCHAR(60) NOT NULL,
    genero VARCHAR(25) NOT NULL,
    especialidade VARCHAR(45) NOT NULL,
    salario DECIMAL (7,2) ZEROFILL UNSIGNED NOT NULL
)
ENGINE = InnoDB;

CREATE TABLE `OficinaMecanica`.`EnderecoMecanico` (
	mecanico_CPF VARCHAR(14) PRIMARY KEY NOT NULL,
    UF CHAR(2) NOT NULL,
    cidade VARCHAR(45) NOT NULL,
    bairro VARCHAR(45) NOT NULL,
    rua VARCHAR(60) NOT NULL,
    numero INT UNSIGNED NOT NULL,
    complemento VARCHAR(45),
    CEP VARCHAR(9) NOT NULL,
    FOREIGN KEY (mecanico_CPF) REFERENCES Mecanico (CPF)
		ON UPDATE CASCADE
        ON DELETE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`TelefoneMecanico` (
	idTelefone INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    numero VARCHAR(15) UNIQUE NOT NULL,
    mecanico_CPF VARCHAR(14) NOT NULL,
	FOREIGN KEY (mecanico_CPF) REFERENCES Mecanico (CPF)
		ON UPDATE CASCADE
        ON DELETE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`Cliente` (
    CPF VARCHAR(14) PRIMARY KEY UNIQUE NOT NULL,
    nome VARCHAR(60) NOT NULL
)
ENGINE = InnoDB;

CREATE TABLE `OficinaMecanica`.`EnderecoCliente` (
	cliente_CPF VARCHAR(14) PRIMARY KEY UNIQUE NOT NULL,
    UF CHAR(2) NOT NULL,
    cidade VARCHAR(45) NOT NULL,
    bairro VARCHAR(45) NOT NULL,
    rua VARCHAR(60) NOT NULL,
    numero INT UNSIGNED NOT NULL,
    complemento VARCHAR(45),
    CEP VARCHAR(9) NOT NULL,
    FOREIGN KEY (cliente_CPF) REFERENCES Cliente (CPF)
		ON UPDATE CASCADE
        ON DELETE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`TelefoneCliente` (
	idTelefone INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    numero VARCHAR(15) UNIQUE NOT NULL,
    cliente_CPF VARCHAR(14) NOT NULL,
	FOREIGN KEY (cliente_CPF) REFERENCES Cliente (CPF)
		ON UPDATE CASCADE
        ON DELETE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`Veiculo` (
	idVeiculo INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    placa VARCHAR(7) UNIQUE NOT NULL,
    modelo VARCHAR(25) NOT NULL,
    marca VARCHAR(25) NOT NULL,
    ano VARCHAR(4) NOT NULL,
    descricao VARCHAR(60) NOT NULL,
    cliente_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (cliente_CPF) REFERENCES Cliente (CPF)
		ON UPDATE NO ACTION
        ON DELETE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`OrdemServico` (
	idOS INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    dataEmissao DATE NOT NULL,
    dataPrevista DATE NOT NULL,
    dataConclusao DATE,
    valorTotal DECIMAL (7,2) ZEROFILL UNSIGNED NOT NULL,
    idVeiculo INT NOT NULL,
	FOREIGN KEY (idVeiculo) REFERENCES Veiculo (idVeiculo)
		ON UPDATE NO ACTION
        ON DELETE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`EquipeMecanicos` (
	idEquipe INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    mecanico_CPF VARCHAR(14) NOT NULL,
    idOS INT NOT NULL,
    FOREIGN KEY (mecanico_CPF) REFERENCES Mecanico (CPF)
		ON UPDATE NO ACTION
        ON DELETE CASCADE,
	FOREIGN KEY (idOS) REFERENCES OrdemServico (idOS)
		ON UPDATE NO ACTION
        ON DELETE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`Servico` (
	idServico INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    mecanico_CPF VARCHAR(14) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    valor DECIMAL (7,2) ZEROFILL UNSIGNED NOT NULL,
	descricao TEXT,
	nome VARCHAR(45) NOT NULL
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`OS_Servicos` (
	idEquipe INT NOT NULL,
    idServico INT NOT NULL,
    FOREIGN KEY (idEquipe) REFERENCES EquipeMecanicos (idEquipe)
		ON UPDATE NO ACTION
        ON DELETE CASCADE,
	FOREIGN KEY (idServico) REFERENCES Servico (idServico)
		ON UPDATE NO ACTION
        ON DELETE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`Peca` (
	idPeca INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    nome VARCHAR(20) NOT NULL,
    quantidade INT UNSIGNED NOT NULL,
    valor DECIMAL (6,2) ZEROFILL UNSIGNED NOT NULL,
	modelo VARCHAR(20) NOT NULL,
    ano VARCHAR(4) NOT NULL,
    marca VARCHAR(20) NOT NULL
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`Servico_Pecas` (
	idPeca INT NOT NULL,
    idServico INT NOT NULL,
    FOREIGN KEY (idPeca) REFERENCES Peca (idPeca)
		ON UPDATE NO ACTION
        ON DELETE NO ACTION,
	FOREIGN KEY (idServico) REFERENCES Servico (idServico)
		ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`Compra_Pecas` (
	idCompra INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    valor DECIMAL (7,2) ZEROFILL UNSIGNED NOT NULL,
    `data` DATETIME NOT NULL,
    cliente_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (cliente_CPF) REFERENCES Cliente (CPF)
		ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OficinaMecanica`.`Compra_Carrinho` (
	idPeca INT NOT NULL,
    idCompra INT NOT NULL,
    FOREIGN KEY (idPeca) REFERENCES Peca (idPeca)
		ON UPDATE NO ACTION
        ON DELETE NO ACTION,
	FOREIGN KEY (idCompra) REFERENCES Compra_Pecas (idCompra)
		ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
ENGINE = InnoDB;


